overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-ods3.yml
targets:
  - README.rst: custom_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - .gitignore: commons-gitignore.jj2
